version: '3.2'

services:
   influxdb:
    build: influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
      - '2003:2003'
   telegraf:
    build: telegraf
    env_file: configuration.env
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'
   grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      
volumes:
  grafana_data: {}
  influxdb_data: {}